### ISSUE TITLE
unhandled exception on connection problem

### ISSUE THREAD

**Issue by brandonmp** [6RiverSystems/bunyan-logsene#61]
A script I'm running had a brief connection interruption.  The script was using `bunyan-logsene` for logging, and it looks like the interruption caused an unhandled exception:

```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Logsene.emit (events.js:163:17)
    at Request.httpResult [as _callback] (/home/bmp/code/project/node_modules/logsene-js/index.js:245:12)
    at self.callback (/home/bmp/code/project/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/bmp/code/project/node_modules/request/request.js:816:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Is there a way to prevent this from killing the process?

**Comment by pranspach** [comment]
We can choose to reemit errors In bunyan >1.7.0. In logsene-js, they emit an object from http errors, not an Error object. 

This library wraps `client.log` in a try-catch, but since this isn't an "Error", the catch never catches the error object.

In bunyan-logsene's constructor, we could add this: 
```
var errorHandler = function(_this) {
  return function (error) {
    _this.emit('error', error);
  }
}(this);
this._client.on('error', errorHandler);
```

In your client code, include remmitErrorEvents and your error handler:
```
const log = bunyan.createLogger({
  name:  'default-js-logger',
  serializers: bunyan.stdSerializers,
   streams: [
      {
        level: process.env.LOGSENE_LEVEL || 'warn',
        stream: logseneStream,
        type: 'raw',
        reemitErrorEvents: true
      }
    ]
});
log.on('error', function (err, stream) {
  console.error('Error logging.');
});
```

I could put this up for a PR, but I'm open to cleaner implementations.

**Comment by otisg** [comment]
Please note the recent change in logsene-js 1.1.42 that has to do with error handling: https://github.com/sematext/logsene-js/commit/66d558492ab6903789c2d1801171746820863067
This 403 handling is specifically about one hitting the Max Daily Log Volume limit.

**Comment by jbcpollak** [comment]
We will update this library to the latest logsene-js shortly (ETA ~2 weeks or so)
